project:
  output-dir: _book/_slides
  render:
    - index.qmd
    - plan-de-cours.qmd
    - introduction.qmd
    - theorie-formats.qmd 
    - exercice-markdown.qmd
    - bonnes-pratiques.qmd
    - encodage.qmd



bibliography: references.bib

format: 
  revealjs: 
    footer: HNU6051-A24
    theme: ["slides.scss"]
    slide-number: true
    slide-level: 3
#filters: 
#  - relevel_headings.lua